### ISSUE TITLE
Input Keyboard Issues

### ISSUE THREAD

**Issue by mschanteltc** [oppia/oppia-android#2133]
- [ ] When the input is selected, scrolling up when the input bar is no longer visible deselects it. Tapping on the keyboard does not enter numbers anywhere but selected numbers on the keypad become bolder. (Image below)[[Video](https://drive.google.com/file/d/1f_1geqB8qaa95xwuKwSU8ya6aMQHiM8v/view?usp=sharing)]

- [x] When input is entered, and the screen is rotated, the entered input is deleted. [[Video](https://drive.google.com/file/d/1f0GYDh1RtaaYhspmj8d9IwXB85Lgnx0E/view?usp=sharing)] Fixed in https://github.com/oppia/oppia-android/pull/5617

- [x] When creating a 3-Digit Input, tapping "Next" after entering the first PIN does not change the input to the second PIN input. Instead, it changes to an "Enter" button that does nothing. [[Video](https://drive.google.com/file/d/1gQ2bznLJtQx15Ii32PQFx-njqqDA8UJs/view?usp=sharing)] Fixed

![Screenshot_20201120-005025_Oppia](https://user-images.githubusercontent.com/22177674/99841268-bb86fb00-2b22-11eb-9a1f-669a8776d95b.jpg)

Device: Might be Samsung device

**Comment by krishnakeshan** [comment]
Could you specify the steps to navigate to the screen you mentioned in the issue?

**Comment by rt4914** [comment]
> Could you specify the steps to navigate to the screen you mentioned in the issue?

@krishnakeshan Welcome to oppia. 
Actually this is something that you won't be able to check on current code. Therefore I am assigning this to myself.

Also, before we start please checkout our [wiki](https://github.com/oppia/oppia-android/wiki) first. This will help you in setting up the project and once you sign the CLA and fill the survey form we can assign you issues to work on.

**Comment by krishnakeshan** [comment]
Hi @rt4914 thanks! Oh alright got it, no worries.

I've signed the CLA and filled out the survey, and have a build running on a device. I'm checking out the wiki right now!

**Comment by rt4914** [comment]
> Hi @rt4914 thanks! Oh alright got it, no worries.
> 
> I've signed the CLA and filled out the survey, and have a build running on a device. I'm checking out the wiki right now!

@krishnakeshan Can you please check if the CLA and the survey was filled successfully because I am not able to find you details in our records.

**Comment by krishnakeshan** [comment]
> > Hi @rt4914 thanks! Oh alright got it, no worries.
> > I've signed the CLA and filled out the survey, and have a build running on a device. I'm checking out the wiki right now!
> 
> @krishnakeshan Can you please check if the CLA and the survey was filled successfully because I am not able to find you details in our records.

Hey @rt4914 sorry my bad on the survey, it turns out I didn't complete it last time. Done now. On the CLA though, I'm getting a "You've already responded" screen on visiting that form, so I'm pretty sure I've filled that out. Let me know!

**Comment by rt4914** [comment]
> > > Hi @rt4914 thanks! Oh alright got it, no worries.
> > > I've signed the CLA and filled out the survey, and have a build running on a device. I'm checking out the wiki right now!
> > 
> > 
> > @krishnakeshan Can you please check if the CLA and the survey was filled successfully because I am not able to find you details in our records.
> 
> Hey @rt4914 sorry my bad on the survey, it turns out I didn't complete it last time. Done now. On the CLA though, I'm getting a "You've already responded" screen on visiting that form, so I'm pretty sure I've filled that out. Let me know!

Great. @anandwana001 will be reaching out to you within next 24 hours. Thanks.

**Comment by anandwana001** [comment]
> > > > Hi @rt4914 thanks! Oh alright got it, no worries.
> > > > I've signed the CLA and filled out the survey, and have a build running on a device. I'm checking out the wiki right now!
> > > 
> > > 
> > > @krishnakeshan Can you please check if the CLA and the survey was filled successfully because I am not able to find you details in our records.
> > 
> > 
> > Hey @rt4914 sorry my bad on the survey, it turns out I didn't complete it last time. Done now. On the CLA though, I'm getting a "You've already responded" screen on visiting that form, so I'm pretty sure I've filled that out. Let me know!
> 
> Great. @anandwana001 will be reaching out to you within next 24 hours. Thanks.

He has filled the CLA earlier, but we were waiting for the contributor survey, which is done now. @krishnakeshan You are good to send Pull Request now.

**Comment by anandwana001** [comment]
> Could you specify the steps to navigate to the screen you mentioned in the issue?

@krishnakeshan Try to run the app and start with any Topic on the Home screen, go to Lessons tab and start playing the story under it. Also, check the video link added in the issue description.

**Comment by rt4914** [comment]
Unassigned self as this has been solved temporarily by making all keyboard use `text` type only. Keeping this open so that we can keep track of it in long-term.

**Comment by BenHenning** [comment]
Note: whoever works on this should double check that these are still problems that need to be solved.

**Comment by MohitGupta121** [comment]
@adhiamboperes as I try to reproduce this issue and see this issue is already fixed:


https://github.com/oppia/oppia-android/assets/76530270/58c85068-76d0-44e6-9380-e2c6925b2156


https://github.com/oppia/oppia-android/assets/76530270/c1dcfe16-20e9-4d40-8b24-54d4912d80b9



This issue is still exist:
When input is entered, and the screen is rotated, the entered input is deleted. 


https://github.com/oppia/oppia-android/assets/76530270/70e64c45-c9c9-4c64-9bd0-23b920ddb54a

**Comment by adhiamboperes** [comment]
@theayushyadav11, could you please test whether this issue can still be reproduced? I suspect it may have been fixed by https://github.com/oppia/oppia-android/pull/5458. 

You can actually test both prod(released before this fix) and current develop branch.

**Comment by theayushyadav11** [comment]
Hi @adhiamboperes, 

Thank you for considering me for this task. I’ve thoroughly tested the issues mentioned in the current `develop` branch, and here are my observations:  

---

**1. Issue: When the input is selected, scrolling up causes the input bar to become deselected, and tapping on the keyboard does not input numbers. However, selected numbers on the keypad appear bold.**

   - This issue still persists. Additionally, the keyboard vanishes immediately when the screen is scrolled.  
   - Here's the observed behavior:  
 [Video](https://github.com/user-attachments/assets/2298d824-13d2-453c-92ab-f560fd7416d9)

---

**2. Issue: Entered input gets deleted when the screen is rotated.**

   - This issue does not appear to exist anymore when tested on chapters in the `develop` branch.  
   - However, I noticed the same issue persists when entering the admin PIN.  
   - Observations:  
     - Chapters: [Video](https://github.com/user-attachments/assets/9e5bdf05-e6e0-468c-a995-1b8ba95dc4e6)  
     - Admin PIN: [Video](https://github.com/user-attachments/assets/2863bb4d-4b12-4494-8f6e-399487a06554)

---

**3. Issue: When creating a 3-digit input, tapping "Next" after entering the first PIN does not shift the focus to the second PIN input. Instead, it changes to an "Enter" button that does nothing.**

   - This issue appears to have been resolved.  
   - Observed behavior:  
   [Video](https://github.com/user-attachments/assets/651f41e6-fcd0-49ab-8ac5-317ab4f3bcb1)

---

Please let me know if any additional testing or clarification is required. Looking forward to your feedback.

**Comment by adhiamboperes** [comment]
Thanks for this thorough investigation and documentation @theayushyadav11! Could you please submit a fix for part of or all of the issues that still persist? Please let us know if you need support at any point.

**Comment by neeldoshii** [comment]
Thanks @theayushyadav11 for the thorough inputs on reproducing the issue! I am able to reproduce the issue. Since no one is recently working on this issue I would like to work on this?

**Comment by theayushyadav11** [comment]
Hi @neeldoshii, could you please clarify the approach for solving this issue, whether in whole or in part?

**Comment by neeldoshii** [comment]
Hi,
I haven't thought for first & third fix for now. Currently I am only planning is for second issue which is about orientation change. The orientation change causes the whole activity lifecycle recreation which leads to edittext's text value to be lost due to lifecycle recreation. 

I plan to fix the issue by adding a `MutableLiveData` in `PinPasswordViewModel` to store the text input. Then, I'll observe this `LiveData` in `PinPasswordActivityPresenter` to ensure the text persists across configuration changes.

Currently blocked due to bazel sync issues (https://github.com/oppia/oppia-android/discussions/5643#discussioncomment-12373241) in my local system, but I figured out the fix by going through the codebase.

**Comment by theayushyadav11** [comment]
@neeldoshii ,Please feel free to make a PR.
