### ISSUE TITLE
Fix Mathematical Naming in classify rules

### ISSUE THREAD

**Issue by anandwana001** [oppia/oppia-android#2423]
**Describe the bug**
Some of the variables naming related to numbers in `src/main/java/org/oppia/android/domain/classify/rules` and it's test packet are mathematical incorrect. 
example - `NEGATIVE_WHOLE_NUMBER_VALUE_TEST_2` where a whole number cannot be negative. 

**Expected behavior**
Need to fix all such variables name

Follow these comments to solve this issue - https://github.com/oppia/oppia-android/pull/2443#issuecomment-758299254
Reach out to @anandwana001 before start working on this. 

### How to work on this issue
Suggesting few points below on how to solve this particular issue:

1. Let's have a doc where you can list all the types of the number we have.
2. Specify the rules based on those numbers. Example - A whole number can't be negative.
3. You can add rules for all the types of number like a fraction, mixed fraction, Ratio of numbers etc...
4. After completing with doc, either we can fix everything in this PR, but I guess it might make this PR big, so we can divide it into multiple sub-issues.

**Comment by codersanjeev** [comment]
Hi, @anandwana001 I would like to work on this issue.

**Comment by anandwana001** [comment]
@codersanjeev please complete the onboarding instructions before starting with the contributions. https://github.com/oppia/oppia-android/wiki

**Comment by chrk2205** [comment]
@anandwana001 
@codersanjeev 
`NEGATIVE_WHOLE_NUMBER` is mathematically incorrect
In `InteractionObjectTestBuilder.kt` there should not be `isNegative` property for whole number in `createWholeNumber` function
or else we should change this too.

**Comment by yash10019coder** [comment]
Hi @anandwana001 I would like to work on this issue please assign this issue to me I have filled individual and survey form

**Comment by yash10019coder** [comment]
HI I have updated the PR please review now @anandwana001 and @prayutsu

**Comment by bhaktideshmukh** [comment]
@anandwana001 @yash10019coder Can you please assign this issue to me?

**Comment by anandwana001** [comment]
@bhaktideshmukh I would suggest before working on this issue, please investigate if this issue exists or not. 

@rt4914 Could you please check here if we still need this issue or not.

**Comment by rt4914** [comment]
@anandwana001 Yes this issue is still there. @bhaktideshmukh Can work on this.

**Comment by bhaktideshmukh** [comment]
@rt4914 @anandwana001 @yash10019coder I read the issue but still its not clear from where and what I should start up with.
Can anyone please suggest me or assign some specific task hinting with what I should go ahead.

**Comment by yash10019coder** [comment]
you can start from domain/java/test(that green folder)/classify/rules/fractionalinput/
[link](https://github.com/oppia/oppia-android/tree/5801df02317cc3f052d79a3dea8b3becd06bc60d/domain/src/test/java/org/oppia/android/domain/classify/rules/fractioninput)

In this you can find some classes try to find the names which seems odd mathematically 
like an whole number integer in this the thing wrong is it should either be a whole number or a integer so try to find these names in the files and fix them

**Comment by manan1979** [comment]
hi @anandwana001 can i work on this issue

**Comment by seanlip** [comment]
Hi @manan1979, could you please provide an explanation of what your PR will do (with names of files you're changing, what you plan to change in each file, etc.). If it looks good, we can assign you to this issue. Thanks!

**Comment by adityamishra9** [comment]
Please allow me to work on this issue under a bit of guidance

**Comment by adhiamboperes** [comment]
> Please allow me to work on this issue under a bit of guidance

Hi @void-iish can you start working on this by prooviding these details requestsed in the issue description?

1. Let's have a doc where you can list all the types of the number we have.
2. Specify the rules based on those numbers. Example - A whole number can't be negative.
3. You can add rules for all the types of number like a fraction, mixed fraction, Ratio of numbers etc...
4. After completing with doc, either we can fix everything in this PR, but I guess it might make this PR big, so we can divide it into multiple sub-issues.

**Comment by adhiamboperes** [comment]
@void-iish, are you working on this issue?
