### ISSUE TITLE
Bullet points are not aligned properly in Naming Numbers and Rounding Numbers Revision card

### ISSUE THREAD

**Issue by KolliAnitha** [oppia/oppia-android#4516]
**Describe the bug**
Bullet points are not aligned properly in Naming Numbers Revision card

**To Reproduce**
1. Go to Topic 'Place Values'
2. Click on 'Revision'
3. Select 'Naming Numbers
4. Scroll down

**Expected behavior**
All the bullet points should be properly aligned

**Demonstration**
![Screenshot_2022-08-20-21-23-12-59_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/185756345-415cd604-d152-4b85-8ff8-6c8e7d981a68.jpg)
![Screenshot_2022-08-20-21-23-56-05_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/185756361-f09bee3b-a05a-4d47-8d96-6527a19cef38.jpg)

**Environment**
Device name: One plus Nord2 5G
Android version : Android 11
App version : 0.8-alpha-091b45a188

**Comment by seanlip** [comment]
@BenHenning just a note, I think this is an Android HTML rendering issue. It looks fine on Web (apart from some spacing issues):

![Screenshot from 2022-08-21 21-31-38](https://user-images.githubusercontent.com/10575562/185840065-47681d74-80d6-40c9-8e9b-1d58d186c696.png)

**Comment by BenHenning** [comment]
Now that #1390 is completed, can you re-check this @KolliAnitha? We've fixed nested alignment issues generally, so I'm hoping that this looks correct now.

**Comment by KolliAnitha** [comment]
@BenHenning, I have rechecked the issue in beta version, it looks the same. Please find the below screenshot.
![Screenshot_2022-09-15-05-54-34-30_943a62cb4c6fb83e010e1c2e82766a17.jpg](https://user-images.githubusercontent.com/101634267/190285694-a7e33841-ada0-4976-9fde-f04863d87556.jpg)

**Comment by BenHenning** [comment]
Thanks @KolliAnitha! It looks like the horizontal spacing is fixed now, but there appears to be extra vertical spacing (maybe from extra tags).

**Comment by BenHenning** [comment]
@KolliAnitha how does this look in the latest beta version? I suspect it's fixed now with the bullet point work that was completed for the first beta release.

**Comment by KolliAnitha** [comment]
Hi @BenHenning, verified in 0.10-beta-5e64fae55e it still looks the same. Please find the below screenshot.
![Screenshot_20230412-093717.jpg](https://user-images.githubusercontent.com/101634267/231347289-0d806046-764c-440f-8573-dd079004dcfa.jpg)

**Comment by BenHenning** [comment]
Ah thanks for checking again @KolliAnitha.

I checked again and I actually think 0290ef8037f798d8ba2721441612a80dec4a1f1a has the fix for this, but it hasn't been released broadly yet. I'll be going out in the next beta release, so we can recheck this then. Adding it to the beta release blocking list so we don't lose track of it.

**Comment by BenHenning** [comment]
Marking this as fixed since it's technically done, and will need to be verified.

**Comment by KolliAnitha** [comment]
The alignment issues is still seen in Naming Numbers.
![subject (11)](https://github.com/oppia/oppia-android/assets/101634267/42df74af-f170-43b9-9398-edfc3544f69a)
