### ISSUE TITLE
[BUG]: Misformatted Text - Special character - Portuguese

### ISSUE THREAD

**Issue by adhiamboperes** [oppia/oppia-android#5200]
### Describe the bug

The special caracter "Ã" is unformatted on chapter 4 of Fractions.

### Steps To Reproduce

1. Open Fraction topic
2. Open chapter 4
3. Second screen already presents the bug

### Expected Behavior

Text should be "não" "questão" "são"

### Screenshots/Videos

![image](https://github.com/oppia/oppia-android/assets/59600948/737d5356-cf32-473c-8b1c-c7b1f9930a6a)

### Which version of the Oppia Android app are you using?

0.11 Beta

### Additional Context

This also happens on web at: https://www.oppia.org/explore/rfX8jNkPnA-1?story_url_fragment=matthew-visits-the-bakery&topic_url_fragment=fractions&classroom_url_fragment=math&node_id=node_4

The affected asset file is `rfX8jNkPnA-1.pb`

**Comment by adhiamboperes** [comment]
I found this in assets as far back as beta 0.9

**Comment by seanlip** [comment]
Update: This has now been fixed on the website.

**Comment by Tushar-kalsi** [comment]
Hi , 
Can i get the opportunity to work on this ??

**Comment by adhiamboperes** [comment]
> Hi , Can i get the opportunity to work on this ??

Hi, there's nothing to be done here at the moment - the issue has been fixed on web. 
Can you look at #4072 or select an item from #5169?

**Comment by seanlip** [comment]
@adhiamboperes Just to check, is this issue supposed to still be open (given that it's been fixed in the content)? Asking since it's on the hotlist for the 0.12 release.

Thanks!

**Comment by adhiamboperes** [comment]
@seanlip, we need to download the latest assets to go out in 0.13 for this to be closed. I have moved the issue to the 0.13 milestone.

**Comment by Rd4dev** [comment]
Hi @adhiamboperes, I reviewed Chapter 4 of Fractions in **Portuguese** and found that every special character "**Ã**" is formatted correctly ( "não" "questão" "são"). However, I did find three instances where the statements are not properly translated.

### 1. next
![36](https://github.com/oppia/oppia-android/assets/122200035/8054de64-891a-473b-9050-3226ecaae282)

### 2. great
![38](https://github.com/oppia/oppia-android/assets/122200035/93659df6-c0f5-494d-b47c-c556e5f5ff37)

### 3. $
![37](https://github.com/oppia/oppia-android/assets/122200035/9f3cf1c8-0298-4742-995b-787f383ee682)

### Other reference Instances where they are properly translated 
![39](https://github.com/oppia/oppia-android/assets/122200035/7b600fa0-aa75-4d47-8784-0175929a23fb)

Although this isn't directly related to the unformatted "Ã," I thought it would be helpful to include this information here for reference.

**Comment by seanlip** [comment]
Hi @Rd4dev, thank you so much for finding these! I confirm that "próxima" and "Ótimo!" have been corrected on the website. Note that R$ is correct though (it is the unit of currency in Brazil, reais), so I did not fix that one.

@adhiamboperes @BenHenning FYI re the content updates here, and just noting generally that this bug on the Android app should be fixed the next time the Android content is downloaded. (Not sure if that means we can close this issue, or if we need to wait until the content download is done in order to close it.)

**Comment by adhiamboperes** [comment]
Closing this since it nolonger reproduces.
