### ISSUE TITLE
[BUG]: Dark mode makes it difficult to see some images and LaTeX

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppia-android#5792]
### Describe the bug

Sometimes certain images and LaTeX renderings are not very easy to see in dark mode contexts.

### Steps To Reproduce

See child issues.

### Expected Behavior

Images and LaTeX need to be visible in dark mode.

### Additional Context

See https://github.com/oppia/oppia-android/issues/6087 for the tracking issue on the lesson side.

The main solution here is likely to re-render LaTeX to respect night mode by using a night mode-compatible color. See https://github.com/oppia/oppia-android/issues/5773#issuecomment-3715775001 for a detailed write-up on what is needed to find a solution to this problem. Combined with the lesson team replacing embedded math content with the math tag, this problem should be fully solvable.

Note: we also need to remove support for rendering the direct SVG image for math, but that requires validating that all math tags correctly contain LaTeX (per #6086): https://github.com/oppia/oppia-android/blob/8dd48de787977567859e3dc8bf5ee3a6980f471d/utility/src/main/java/org/oppia/android/util/parser/html/MathTagHandler.kt#L54-L62

Also related: #6086.

**Comment by BenHenning** [comment]
Bumping to high impact since the usability issues can provide very significant contrast issues and make some of the content likely impossible to play for users without switching off dark mode (which might be difficult for systems that automatically select dark mode).

I'm also thinking that we could update the lesson download script to try and detect a transparent background. This is a hard problem to solve inherently and may require rendering images and sampling to determine their background color. Need to think on this more.

**Comment by adhiamboperes** [comment]
Adding some past context:
https://github.com/oppia/oppia-android/pull/5141 fixed an issue where the some OEMs invert colors in darkmode, but we only implemented this for thumbnail images. 

We further discussed fixing this color inversion as related to #5047 (see issue comments). 

Pulling from CLaM meeting notes on this issue:

- Mohit's and Adhiambo’s devices don’t display images correctly in dark mode.
   - There is a theory that these devices do not have proper dark mode support because of an OEM-specific configuration that conflicts with AOSP darkmode support.
   - Stackoverflow suggests adding an “force dark allowed” attribute to the imageview, but we don’t want to ever have to do this.
- If an app image (not content image) needs inversion, then we might just want to have two versions of that image.
- We might want to pre-fill a white background to the embedded content images before rendering the backgrounds. We Don't want the white background to bleed beyond the image, so it should blend into the image and not be visible at all otherwise. We know the size of the image in UrlImageParser and the background should be about the same size. If the image has a transparent background, we override it.
   - This implies changes in the UrlImageParser. Some additional blending work will be needed so that the transparent image background actually blends with the white background.
- To clarify, there are two separate darkmode issues:
   - Inversion in the thumbnail images - a problem with a property of the image view
   - Background color in the embedded content images

**Comment by adhiamboperes** [comment]
Comparing my device (Xiaomi Redmi) with @cam-pinheiro's (OPPO A79):

|Xiaomi Redmi | OPPO A79|
|--|--|
|![Image](https://github.com/user-attachments/assets/2e84bff5-d309-4835-b208-b088f1929173)| ![Image](https://github.com/user-attachments/assets/bee6f259-0ad7-4c66-b8da-9a89cabbe6c9)|
|![Image](https://github.com/user-attachments/assets/1743221d-e084-4fb0-b4eb-ddea4e743595)| https://github.com/user-attachments/assets/cd5cb28e-cc0a-4808-b504-7bcaffcdb45a |

Different types of images behave differently, and we should check to see which image formats are affected.

**Comment by adhiamboperes** [comment]
## Known issues per OEM

| OEM               | Issue                                                                 | Notes                                                                 |
|------------------|-----------------------------------------------------------------------|-----------------------------------------------------------------------|
| **Samsung (One UI)** | Sometimes **ignores `android:forceDarkAllowed="false"`**, forcibly darkens app UI even when disabled. | Affects WebViews, backgrounds, and images.                            |
| **Xiaomi (MIUI)**    | **Aggressive forced dark mode**, even for apps that don’t want it. | Causes inverted colors, broken UIs unless explicitly opted out.       |
| **OPPO / Realme (ColorOS)** | Forcibly darkens apps, even WebViews, and sometimes breaks contrast and visibility. | Custom settings per app may override developer intent.               |
| **Vivo (FuntouchOS)** | May apply dark mode selectively or inconsistently.               | Theme switching may cause silent activity restarts.                   |
| **Huawei (EMUI)**    | Inconsistent system night mode APIs; may not fully support AppCompat themes. | Testing on device is important due to behavior divergence.            |
| **Pixel / AOSP**     | Generally follows official behavior closely.                      | Safe baseline for testing.                                            |

**Comment by adhiamboperes** [comment]
Hi @cam-pinheiro,

I noticed some differences in how dark mode is affecting the app on our devices: on your Oppo (Android 14), some images display correctly that appear inverted on my Xiaomi (Android 11), and vice versa.

To help narrow this down, could you please check and let me know which dark mode setting you're using on your device? For example:

- Is system-wide dark mode turned on or off?
- Are there any per-app dark mode overrides for our app in your phone settings?
- Are you using any "enhanced" or "forced" dark mode options?

This will help us better understand how your device is applying dark mode so we can isolate the issue.

Thanks a lot!

**Comment by cam-pinheiro** [comment]
Hi @adhiamboperes,
I’m using the system-wide dark mode.

**Comment by CodeWithSangeeta** [comment]
Hi, I’d like to work on this issue if it’s still available. 
I plan to pick one specific UI case affected by dark mode and investigate it.
Please let me know if that’s okay.

**Comment by adhiamboperes** [comment]
@CodeWithSangeeta, please feel free to look into this and share your findings in this thread. Hopefully my previous investigations will provide some pointers.

**Comment by CodeWithSangeeta** [comment]
Thanks! I’ll look into this and share my findings. I’ll also review the previous investigation notes for guidance.

**Comment by adhiamboperes** [comment]
@CodeWithSangeeta, could you please also see the new discussion in https://github.com/oppia/oppia-android/issues/5773#issuecomment-3723985579?

**Comment by CodeWithSangeeta** [comment]
@adhiamboperes, Thanks for the clarification. Based on the discussion, I understand that Oppia renders fractions via two pipelines: LaTeX-based rendering (KotliTeX) and embedded content images via UrlImageParser. Since LaTeX already supports color handling, I’ll focus my investigation and fix on the embedded content image pipeline in UrlImageParser, where transparent bitmaps lead to contrast issues under forced OEM dark mode.

**Comment by BenHenning** [comment]
Note that I updated the PR description to have more specifics on the solution I suspect we want to take.

Note that I think we should have just one person assigned to this top-level issue rather than the constituent issues @adhiamboperes since they probably all have the same solution.

**Comment by BenHenning** [comment]
FYI @CodeWithSangeeta I updated the PR description to include another requirement.

As far as I can tell there are three possibilities that could lead to the broken state:
1. Lessons are using direct images of math rather than the math tag (@seanlip and I both think this is unlikely, and it requires an audit of production lesson images a la #6086 to validate).
2. Math tags are broken in some cases and are missing LaTeX which would result in the app falling back to svg filenames. This actually seems very likely. We need to validate this via #6086 but we can also try validating it by removing that part of the `MathTagHandler` and testing the app with production lessons in the cases we know are broken.
3. We're rendering the LaTeX within the app with the wrong color (the original solution I outlined earlier).

I think you should start with (3) and, when it's ready to test, you can also include (2) since removing that part of `MathTagHandler` is at least easy for testing and then we can try out a branch with production assets to see if the issue is fixed. We'd probably still want to complete #6086 before fully accepting that this issue is addressed, but I strongly suspect fixing (2) and (3) will probably full fix things.

**Comment by CodeWithSangeeta** [comment]
Thanks again for the guidance. I followed your suggestion to start with (3) and traced how LaTeX rendering color is currently handled.

Based on the pipeline you outlined (and the discussion in #5773), I found that LaTeX math is rendered via `MathExpressionSpan`, with the color coming from a fixed resource (`component_color_shared_equation_color`) fetched without a theme. This explains why the math color doesn’t adapt correctly between light and dark mode.

From this, it seems the correct direction is to derive the LaTeX color from the theme’s text color so it stays consistent with surrounding lesson content and accessibility expectations.

I’ll continue digging into how best to pipe a theme-resolved text color into the LaTeX rendering path and share next steps. Thanks for pointing me in the right direction.

**Comment by CodeWithSangeeta** [comment]
Hii @BenHenning,

One clarification I wanted to confirm before proceeding further. Although LaTeX appears inline with lesson text, my understanding is that it’s rendered as a bitmap via KotliTeX before being inserted into the TextView. Because of this, spans or TextAppearance applied to surrounding text can’t affect its color after rendering.

Based on that, it seems the correct approach for (3) is to resolve the theme’s lesson text color up front and pass it into the LaTeX rendering path (e.g., MathExpressionSpan), rather than trying to style it afterward.

I’m planning to start by validating this approach for (3). Once that’s in a testable state, I can also look into (2) by temporarily bypassing the fallback path in MathTagHandler to help validate whether broken/missing LaTeX is contributing to the issue in known production cases.

Before going further, I just wanted to check that this understanding and direction align with your expectations, and whether there’s a preferred theme attribute/source you’d recommend using for the lesson body text color.

Thanks!

**Comment by CodeWithSangeeta** [comment]
Hi @BenHenning,

I wanted to share a brief update on Option (2) based on my investigation so far.

I traced how `math_content-with-value` is handled in `MathTagHandler`. The current logic prefers `svg_filename` over` raw_latex`:
```

when {
  svgFilename != null -> MathAsSvg(svgFilename)
  rawLatex != null -> MathAsLatex(rawLatex)
}

```

This means that whenever `svg_filename` is present, math is rendered via the SVG image path (ImageSpan), even if LaTeX exists. From what I can see, this would explain why some cases appear as “LaTeX issues” but are actually SVG dark-mode incompatibilities.

I followed the generation path of `math_content-with-value` (e.g. `SolutionViewModel`, `MathExpressionParserViewModel`,etc.) and attempted to validate this locally, but I wasn’t able to reliably reproduce the problematic SVG cases in the dev build. This seems consistent with the issue being driven by production lesson content or legacy assets, rather than the Android rendering logic itself.

Based on this, my current understanding is that Option (2) is mainly about validation/detection of lesson content (missing/invalid LaTeX or SVG-based math), rather than a direct client-side rendering fix.

I wanted to confirm that this interpretation of Option (2) aligns with your expectations or not.
I’m happy to investigate further in whatever direction you think is most useful next.

Thanks!

**Comment by BenHenning** [comment]
That's a really good finding @CodeWithSangeeta and I missed that. I think you're correct as to why we're defaulting wrong here (though we still want to remove the SVG loading path outright since we can never get it to look correct). We need to perform a deeper audit on (2) so I think your findings are a good place to stop at this point until we can actually update the lesson download script to analyze all of the math tags being imported.

I think your plan for (3) sounds correct to me, as well, for how to handle the color and pass it down to the LaTeX rendering layer.

This overall finding does worry me slightly, though. It means we've been largely testing all of the app content for the last couple years without the KotliTeX pipeline being used. That means there's a risk in regressing behavior. I need to think on this a bit more, but we may actually want to consider introducing a feature flag that defaults LaTeX rendering to never using the SVG and test that with the QA team in isolation in case there's a risk of regression. I suggest that, for now, continue with your investigation and work as-is and I may suggest this change once a PR is raised (it will be a simple change, but we'll need to make some additional tracking issues to make sure this can get tested and released as a proper feature, maybe in the 0.19 release).

**Comment by CodeWithSangeeta** [comment]
Hi @BenHenning,

Thanks for the clarification — that really helps align the direction.

I’ll proceed with implementing (3), i.e. resolving the theme’s lesson body text color up front and explicitly passing it into the LaTeX/KotliTeX rendering path, keeping the change scoped to LaTeX only as discussed.

One thing I wanted to flag before going too far: in the dev build, the original issue isn’t fully reproducible. I’ve only been able to reproduce it on one specific screen, and even there the behavior is inconsistent across runs and modes, which makes validation a bit tricky.

For validation, my plan is to:
- Ensure the resolved LaTeX color visually matches the surrounding lesson body text in both light and dark mode.
- Test with LaTeX caching disabled to avoid any stale renders while validating the change.

One small clarification I wanted to align on: when resolving the color to pass into KotliTeX, there are multiple Material/theme attributes available (e.g., primary, surface, onSurface, etc.). My current assumption is that we should derive the same color used for lesson body text (rather than a semantic color), so LaTeX stays visually consistent with surrounding content and adapts correctly across themes and OEM variations. Please let me know if there’s a preferred theme attribute or existing text style you’d recommend using as the source of truth here.

 Happy to adjust the validation approach if you’d like this tested against specific screens, flags, or QA expectations.

Thanks again!

**Comment by BenHenning** [comment]
@CodeWithSangeeta defaulting to text color sounds correct (@adhiamboperes to confirm if there's a different color we should use). If it ends up looking a bit odd once you have a fix to share, we can consult with the Android UX design team to get their thoughts, but I suspect matching the color is the best approach.

The inconsistency isn't _too_ surprising because of caching, so yes disabling caching is definitely the best option. It may not fully solve the problem, though, so on occasion you may need to clear the app's cache (not data files, just cache) via app settings on your device/emulator. The app's cache folders are primarily populated by Glide images, so clearing them will force Glide to re-load (which, in turn, will re-render LaTeX). It's important to understand the distinction here:
- LaTeX caching (per the `CacheLatexRendering` platform parameter) is actually using two separate pipelines: real-time LaTeX rendering using KotliTeX's own `MathExpressionSpan` and converting the LaTeX into an SVG first (and caching it via Glide), then rendering the SVG directly.
- Glide caching (which isn't something we have a flag to configure) which automatically happens for all images (SVG & otherwise) loaded in the app.

The reason this distinction is important is because they technically use different pipelines. `MathExpressionSpan` does draw calls directly and doesn't even use the SVG conversion pipeline from KotliTeX (we're considering removing that pathway entirely, but now that we know we haven't even been testing it we need to reevaluate), which in turn means it may require a different color customization strategy. It's fine to start with this to keep things easy, but once you have that working you probably should turn LaTeX rendering back on and make sure it still works (including when switching between night/day modes), resetting the Glide cache as mentioned above as needed.

**Comment by CodeWithSangeeta** [comment]
Hi @BenHenning ,

Quick update on Option (3). I’ve implemented the change to resolve the theme’s lesson body text color and pass it explicitly into the LaTeX/KotliTeX rendering path (via MathExpressionSpan), keeping the change scoped strictly to the LaTeX pipeline.

For validation, I disabled LaTeX caching locally and tested the fix on the one screen in the dev build where I’m able to reproduce the issue. With the change applied, the LaTeX color now consistently matches the surrounding lesson body text in both light and dark mode on that screen.

One thing I noticed after the change is a slight layout difference: the rendered LaTeX content appears a bit more left-aligned compared to before (previously it looked more right-shifted). I’ve attached a screenshot to show the before behavior, along with a short screen recording demonstrating the after behavior for additional context.

**Before (screenshot):**  
<p align="center">
  <img src="https://github.com/user-attachments/assets/fa2a09f5-dd61-476f-886c-91dd67b94f0b" width="200"/>
</p>

**After (screen recording):**  
▶️ https://drive.google.com/file/d/1iJkoEmfMUYU4ql8RmCstFTEz7AL5lrwX/view

Please let me know if this alignment change is expected/acceptable from your perspective, or if you’d prefer me to investigate and adjust it. I’m happy to iterate further based on your guidance.

Thanks!

**Comment by BenHenning** [comment]
Thanks @CodeWithSangeeta. The color definitely looks much better.

This is an alignment issue that I think we fixed, but perhaps only with the `ImageView`-exclusive approach (/cc @adhiamboperes who worked on this extensively, though that might have been limited to just SVGs per #5208).

Does the centering get fixed if you re-renable caching but still keep the SVG filename loading bit disabled? That would run the LaTeX through the SVG rendering pipeline rather than directly rendering it in KotliTeX, so I would expect it to work correctly.

And, in fact, that might force us to simply abandon both other rendering pipelines and permanently keep caching as the only way to render LaTeX in the long-term (which seems completely reasonable to me).

**Comment by adhiamboperes** [comment]
@CodeWithSangeeta, cc @BenHenning,

I tested turning off caching latex rendering, and was able to repro the alignment issue -- so it is not related to the color changes that you have made.

<img width="300" height="640" alt="Image" src="https://github.com/user-attachments/assets/8301eec1-c8ec-4501-97bd-b6bc4e3131e6" />

And yes, https://github.com/oppia/oppia-android/pull/5208 only covered alignment issues in svgs, since that was the main issue in #5112.

**Comment by CodeWithSangeeta** [comment]
Hi ,quick update:

While testing the “enable caching + disable SVG path” scenario, I’m currently hitting a crash in the dev build. Logcat shows a Resources$NotFoundException coming from MathBitmapModelLoader.kt when resolving the theme-based text color (it looks like an invalid resource ID is being passed into ResourcesCompat.getColor()).

I’ll investigate ,fix and  share the updated results once the crash is resolved.

Thanks!

**Comment by CodeWithSangeeta** [comment]
Hi @BenHenning, @adhiamboperes — quick update with the full investigation results.

**Background / Initial issue**
I was originally seeing a LaTeX alignment issue (LaTeX appears left-aligned instead of centered).
While working on it, I also applied the KotliTeX text color fix (using body text color) and confirmed the color improvement works correctly.

After that, I tested the different rendering pipeline combinations suggested in this thread.

**Tests performed**
✅ Case 1: Caching OFF (direct KotliTeX rendering)

- LaTeX renders correctly (visible).
- Text color looks correct in both light & dark mode.
- Alignment issue is still present (LaTeX is left-aligned).

✅ Case 2: Caching OFF + SVG filename loading disabled
- (i.e. forcing LaTeX-only parsing path)
- LaTeX still renders correctly.
- Alignment issue still present (still left-aligned).

❌ Case 3: Caching ON (cached pipeline enabled)

- LaTeX does not render at all (blank space where equation should be).
- Happens in both light and dark mode.
- No crash occurs, and logcat does not show any obvious exception.

❌ Case 4: Caching ON + SVG filename loading disabled ( your suggested scenario)

I disabled the SVG parsing path in `parseMathContent() `like below:

```
val rawLatex = obj?.getOptionalString("raw_latex")
// val svgFilename = obj?.getOptionalString("svg_filename")
return when {
  // svgFilename != null -> MathAsSvg(svgFilename)
  rawLatex != null -> MathAsLatex(rawLatex)
  else -> null
}
```


**Result:**

- LaTeX still does not render (blank).
- Same behavior as Case 3.
- So enabling caching seems to be the key trigger for equations disappearing.

**Debug logs / Evidence**
I added logs in MathTagHandler and MathBitmapModelLoader.

**From logs:**

- `MathTagHandler.handleTag()` is being executed correctly
- LaTeX is being parsed correctly
- Cached pipeline is being called

Example log output:

```
D MathDebug: Parsed content = MathAsLatex(rawLatex=y=mx+b)
D MathDebug: Rendering using LATEX pipeline, cacheLatexRendering=true rawLatex=y=mx+b
D MathDebug: buildLoadData(): width=-2147483648 height=-2147483648 model=y=mx+b
D MathDebug: LatexModelDataFetcher.loadData(): targetWidth=-2147483648 targetHeight=-2147483648 lineHeight=52.0
D MathDebug: Before scaling: targetWidth=-2147483648 targetHeight=-2147483648 SIZE_ORIGINAL=-2147483648

```

This confirms that when caching is enabled, Glide is requesting:

- `width = Int.MIN_VALUE`
- `height = Int.MIN_VALUE`
- which matches `Target.SIZE_ORIGINAL`

So the cached rendering pipeline is definitely being executed, but the final output still becomes blank.

**Current conclusion**

- When caching is OFF, LaTeX renders but is misaligned (left-shifted).
- When caching is ON, LaTeX is completely missing (blank), even when SVG filename loading is disabled.
- Logcat confirms the cached pipeline is triggered and receives `Target.SIZE_ORIGINAL `sizing (`Int.MIN_VALUE`), but no exception is thrown.
- So it looks like the issue is somewhere inside the cached pipeline (MathBitmapModelLoader / Glide sizing behavior) rather than parsing.
- If there’s a recommended dev/test screen that reliably contains multiple LaTeX equations for testing, please let me know and I can verify there too.

Thanks!

**Comment by CodeWithSangeeta** [comment]
Hii,
Just a quick follow-up — could you please take a look at my last investigation/update when you get time and confirm if I’m investigating in the right direction?
I want to make sure I proceed correctly before moving further.

Thanks!

**Comment by BenHenning** [comment]
Apologies--it's been a busy few days.

As discussed in the meeting today I think you're reaching the point where we actually need code to help further on this because if the fix is causing cached images to disappear but cached images normally work without it, there's some disconnect happening very specific to the code itself. I should be able to provide better context once I can see a draft PR that has the changes.

**Comment by CodeWithSangeeta** [comment]
No worries, thanks for the update!

Got it — that makes sense. I’ll create a draft PR with my current changes (including the caching + SVG-disabled experiments and the color fix) so you can review the code directly.

I’ll share the draft PR link as soon as it’s ready. Thanks!

**Comment by CodeWithSangeeta** [comment]
Hi , I’ve created a draft PR with the current investigation changes and logs.
PR: #6099
Please let me know what changes you’d like next.

**Comment by CodeWithSangeeta** [comment]
Hi @BenHenning, quick update — I was able to narrow down the caching blank-render issue further with additional logs.

**Progress**
I added .override(width, height) in `GlideImageLoader.loadMathDrawable() `to ensure Glide does not request `Target.SIZE_ORIGINAL.` After this change, Glide now correctly passes real dimensions into the cached pipeline:

```
buildLoadData(): width=416 height=104
LatexModelDataFetcher.loadData(): targetWidth=416 targetHeight=104
```


So the Int.MIN_VALUE / SIZE_ORIGINAL issue is no longer the blocker.

**What’s happening now**

Even with valid width/height, the cached bitmap rendering still produces a completely empty render.

From logs inside `renderToAutoSizingBitmap():`

```
Pixel scan complete: filledRegionEmpty=true
Render is fully empty -> returning 1x1 bitmap
```


This indicates the LaTeX is going through the cached pipeline, but the resulting bitmap contains no non-transparent pixels, so it gets reduced to a 1x1 bitmap and appears as blank.

**Likely root cause: resolved color is transparent**

While debugging the theme-based color, I logged the value passed into` MathExpressionSpan`. The resolved value looks suspicious:

```
typedValue.type=3
Resolved textColorPrimary = 3121 hex=c31
```


This does not look like a normal ARGB color (e.g. 0xff000000), and since it lacks an alpha component it seems to be effectively transparent. That would explain why the bitmap ends up empty even though rendering executes.

Please let me know  it is in right direction or i missed something ?

Thanks!

**Comment by CodeWithSangeeta** [comment]
Hi @BenHenning ,

Quick update — I was able to resolve the earlier ARGB color resolution confusion.
Previously `typedValue.data` was giving a small value like 0xC31 because the attribute was a reference (type=3). So instead of using `typedValue.data`, I now correctly resolve the actual ARGB color using `ResourcesCompat.getColor()` with `typedValue.resourceId`, which gives a proper value like 0xff1d1b20.

After that, I continued investigating the LaTeX dark mode visibility issue and added detailed logs in the Glide → MathBitmapModelLoader pipeline.

From the logs, the rendering is happening in DARK mode:

`ThemeCheck: nightMode=DARK`

But the resolved textColorPrimary is still coming out as a dark color:

`resolvedColor=ff1d1b20`

Also, the important part is that `MathBitmapModelLoader` is still being created with Application context, not Activity themed context:

`MathBitmapModelLoader context class=org.oppia.android.app.application.dev.DeveloperOppiaApplication`

Because of this, even though the app is in dark mode, the attribute resolution is using the application theme and the generated LaTeX bitmap stays dark, making it hard to see on dark background.

I tried switching to context-based theme resolution and also updated Glide to use `Glide.with(target.imageView.context`) for `ImageViewTarget`, but the LaTeX requests are still going through CustomImageTarget and the ModelLoader continues receiving application context.

At this point it feels like I’m back to the original issue: the bitmap caching pipeline is reusing a color computed from the wrong theme context.

Could you suggest the correct way to pass an Activity/Fragment themed context into this LaTeX bitmap rendering pipeline (or the preferred Oppia theme context to use here)?

Thanks!

**Comment by adhiamboperes** [comment]
@CodeWithSangeeta, the application context is not necessarily an issue here. You can look into using 

```kotlin
ResourcesCompat.getColor(
              application.resources,
              R.color.component_color_shared_equation_color,
              /* theme = */null
            ) 
```

as shared at the meeting today, and also add log statements to `MathBitmapModelLoader` to check what the text primary color is in dark mode specifically. 

https://github.com/oppia/oppia-android/pull/4866 also provides some context on how a similar issue was solved in the past.

**Comment by CodeWithSangeeta** [comment]
Hi , quick update.

I reverted all the previous theme/context-related changes (also removed the override sizing changes), and LaTeX rendering works correctly again.

However, the main issue still seems to be Glide caching the first-rendered theme output:

Case 1: Fresh install → open lesson in Light mode → Light looks correct → switch to Dark → Dark LaTeX looks wrong
Case 2: Fresh install → open lesson in Dark mode → Dark looks correct → switch to Light → Light LaTeX looks wrong

So it looks like the bitmap generated during the first render (based on the current theme color) is cached, and when the theme changes later, Glide still reuses the same cached bitmap instead of re-rendering with the new theme color.

This makes it seem like the cache key does not include theme/night mode state.



Thanks!

**Comment by CodeWithSangeeta** [comment]
Hi @adhiamboperes , quick update on the caching issue investigation.

I confirmed the behavior is caused by Glide reusing the first-rendered cached LaTeX bitmap (Light-first breaks Dark, Dark-first breaks Light), so it looks like the cache key/signature does not include theme/night-mode state.

To test this, I added an isNightMode flag into MathModel and also included it inside `MathModelSignature.updateDiskCacheKey() `so Light/Dark would generate different cache signatures.

After that change, LaTeX images stopped rendering and logcat showed:

`java.nio.BufferOverflowException`

<img width="2879" height="780" alt="Image" src="https://github.com/user-attachments/assets/307bbf44-2f6b-4a4f-a503-178a3c681a54" />

I found the cause: in` updateDiskCacheKey()` I added one extra byte for night mode but forgot to increase the `ByteBuffer.allocate()` size properly (needed +2 bytes since two flags are written). After fixing the allocation size, the crash is resolved.

Does this approach (adding theme/night-mode to the signature/key) seem like the correct direction for properly separating cached renders across themes?

Thanks!

**Comment by CodeWithSangeeta** [comment]
Hi @adhiamboperes,

I tracked the `BufferOverflowException` cause to `ByteBuffer.allocate() `size being too small (I added an extra byte for night mode but didn’t update the allocation size correctly). After fixing the allocation size, LaTeX rendering works correctly again, and caching now separates properly across Light/Dark themes.

I’ve also recorded a short screen recording showing the issue + the fix.
https://drive.google.com/file/d/1MIqQXQjESmsQlkhPOtJyNYsct1DqjNVf/view?usp=sharing

If this approach looks correct to you, I’ll proceed with updating the PR accordingly and Since I already opened a draft PR earlier, should I push these changes to the same draft PR, or would you prefer I open a new PR for this fix?

**Comment by adhiamboperes** [comment]
@CodeWithSangeeta, this sounds good. You can push to the draft PR if you edit the PR to remove unrelated changes. Otherwise you can simply close it and create a fresh one. Thanks!

**Comment by BenHenning** [comment]
Thanks for the continued investigations and write-ups here @CodeWithSangeeta. I'm glad you were able to work toward a solution and the write-up has been really helpful for catching up & keeping updated.

**Comment by CodeWithSangeeta** [comment]
Hi @BenHenning,

As per the three possibilities you suggested, I’ve investigated (2) and implemented the fix for (3) (theme-aware LaTeX rendering + cache separation). I’ve verified the behavior on the screen where the issue was reproducible, and it now works correctly there.

However, I’ve only validated it on that specific case. Could you please take a look and let me know if it works as expected across other affected screens, or if you’d recommend that I proceed further with deeper investigation into (2) or (1)?

Thanks!

**Comment by BenHenning** [comment]
I think we covered this during the team meeting but to summarize: @adhiamboperes offered to test at least some of the sub issue cases to see if this seems to be systemically fixing the core problems (though there was one changed needed in #6109 to actually enable the testing pathway which I think you addressed a bit ago). We may opt to preliminarily mark all of the issues as fixed if the ones @adhiamboperes tests look good and ask QA to verify those as part of the 0.18 release.

@CodeWithSangeeta I think it's definitely worth thinking about how you can test that your changes are working in an automated test. It may be a bit tricky but now is the right time to be thinking about that. If we want these issues tested for 0.18 then your PR will need to be merged by the end of the week (which means there's not a lot of time for back-and-forths on the review itself).

**Comment by CodeWithSangeeta** [comment]
hii @BenHenning ,
I’ve added an automated unit test to verify that MathModel.toKeySignature() now includes isNightMode in the cache signature.
The test ensures that light mode and dark mode models generate different disk cache keys, preventing incorrect cache reuse.
All tests are passing locally. Please let me know if you’d like me to add additional coverage.

**Comment by BenHenning** [comment]
@CodeWithSangeeta depending on where in the pipeline you're accessing the color, it may actually be possible to also test that the correct image is being loaded.

For example, it like makes sense to change `ImageLoader` to require the background color to be passed directly in (which makes `MathTagHandler` responsible for loading the color):

https://github.com/oppia/oppia-android/blob/a17c8ddd22ed986d82570e470ae763be4b6e94cf/utility/src/main/java/org/oppia/android/util/parser/image/ImageLoader.kt#L58

This actually seems like the better approach, anyway, because we were doing this previously for `MathExpressionSpan` in `MathTagHandler`.

Updating `ImageLoader` means that you can actually update `TestGlideImageLoader` as well which will store the actual `MathModel` used for loading. With `MathModel` updated to include the color, now we can use `TestGlideImageLoader` to actually validate that the correct color is being passed via `MathModel` to the image loader as a proxy to assert the correct color was used during image loading. You can look for tests where `TestGlideImageLoader` is used for reference.

**Comment by CodeWithSangeeta** [comment]
Hi @BenHenning,

I wanted to ask about the next steps.

At the beginning of the investigation you suggested looking into three possible causes:

1. Lessons using direct math images instead of math tags
2. Math tags missing LaTeX and falling back to SVG
3. LaTeX rendering with an incorrect color in the app

I started with (3) and implemented the fix for the LaTeX color handling, which has now been merged. I also investigated (2) and shared my findings that the current logic prefers `svg_filename` over `raw_latex`, which may explain why some cases fall back to SVG. At that time you suggested pausing further investigation on (2) until the lesson download script can audit the math tags.

Since some child issues are still open, I wanted to ask what would be the most useful next step:

- Should I continue investigating another potential cause for the remaining cases?
-  Or should I start analyzing the remaining child issues individually to see if they fall under the SVG fallback scenario or a different rendering issue?

Happy to investigate further wherever it would be most helpful.

Thanks!

**Comment by BenHenning** [comment]
Thanks @CodeWithSangeeta. I think you’re correct that #6086 needs to be addresses before we can proceed with work here. Essentially all of the dark mode image issues came down to two cases:
- LaTeX
- Direct image rendering

Your work covers the main parts of the first one, but we do still need to finish it by removing the code pathways that:
- Fallback to the math SVG (we should always be rendering the LaTeX).
- Try to render LaTeX directly without caching (we want to make caching the permanent solution).

However, we can’t do that until the audit is complete to determine whether any lessons would break from that change.

The remaining non-LaTeX issues are much harder to solve because they will likely require a full-stack solution whereby lesson artists can provide dark mode image variants (or will need to recreate images that need better dark mode contrast). This is something the audit will help reveal but the work here becomes more administrative to start (we will need to sync with lessons team), and possibly a full stack project later on.

Does this help clarify?

**Comment by CodeWithSangeeta** [comment]
Yes, this definitely helps clarify—thanks a lot for the detailed explanation!
